apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.1
        env:
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_DATA_DIR
          value: /etcd-data
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://etcd.default.svc:2379"
        ports:
        - containerPort: 2379
        resources:
          limits:
            cpu: "500m"  # Set CPU limit to 500 milliCPU (0.5 CPU)
            memory: "512Mi"  # Set memory limit to 512 MiB
          requests:
            cpu: "100m"  # Set CPU request to 100 milliCPU (0.1 CPU)
            memory: "256Mi"  # Set memory request to 256 MiB
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
      volumes:
      - name: etcd-data
        emptyDir: {}
