# apiVersion: v1
# kind: Service
# metadata:
#   name: etcd
# spec:
#   selector:
#     app: etcd
#   ports:
#     - protocol: TCP
#       port: 2379
#       targetPort: 2379

apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: default
spec:
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
      targetPort: 2379
      nodePort: 30000
      protocol: TCP 
      
  type: NodePort
  